services:
  goservice-test:
    image: goservice:latest
    environment:
      - DB_HOST=${TEST_DB_HOST}
      - DB_PORT=${TEST_DB_PORT}
      - DB_USER=${TEST_DB_USER}
      - DB_PASS=${TEST_DB_PASS}

  goservice-prod:
    image: goservice:latest
    environment:
      - DB_HOST=${PROD_DB_HOST}
      - DB_PORT=${PROD_DB_PORT}
      - DB_USER=${PROD_DB_USER}
      - DB_PASS=${PROD_DB_PASS}
